### ISSUE TITLE
reset to default theme after some time

### ISSUE THREAD

**Issue by olivaresdeveloper** [mallowigi/material-theme-issues#60] opened 2022-01-18 18:18 UTC
**Describe the bug**
I use the monakai pro material theme (anyone is the same). I stop using the editor for a while and the editor restarts the theme by moving it to the deep ocean theme, it happens when I open the app or keep it open but not using it.

**To Reproduce**

1. open editor
2. do not use it for a few minutes

**Expected Behavior**
keep the theme i use

It should contain:
* OS Windows
* WebStorm
* Material Theme UI Pro 6.12.2

NOTE: the "automatically reset color scheme " option is disabled and the error still occurs

**Comment by mallowigi** [comment] 2022-01-19 07:28
Does it happen consistently or after some event? I need to be able to reproduce, I never encountered this issue myself.

**Comment by mallowigi** [comment] 2022-01-19 13:17
I'll try to boot up a windows machine and see if it happens, but I have no idea what might be causing this.

**Comment by mallowigi** [comment] 2022-01-22 15:16
It just happened to me out of the blue. In the first time since forever, and I can't put any themes until I restart...

Really troublesome issue, I hope I can find the culprit.

**Comment by olivaresdeveloper** [comment] 2022-02-16 13:36
I managed to find the error, I realized that the same does not happen with php storm, that I use the material, I have two computers, one in the office and the other at home, when I use webstorm on two computers with different themes, it breaks.
with php storm it doesn't happen to me, I don't know what it has to do with it, but I realized it because of the use, I put the same theme and it didn't happen.

**Comment by mallowigi** [comment] 2022-03-22 05:04
I'm closing this issue as I can't reproduce. I would be glad if you could connect to slack and reproduce it in real time.

**Closed by mallowigi** 2022-03-22 05:04 UTC
Labels: duplicate, sync
