### ISSUE TITLE
[Bug]: The run widget has not to correct color when using the new UI

### ISSUE THREAD

**Issue by an2riy** [mallowigi/material-theme-issues#207] opened 2022-08-10 15:03 UTC
### Describe the bug

During a load of a project or run any action that is time-consuming the run widget has not correct color.

### To Reproduce

1. Use a custom them: **File \> Settings \> Appearance & Behavior \> Appearance \> Theme** where the main color is not blue

2. Enable new UI:

   | ide.experimental.ui | true |
   | --- | --- |

3. Reload IDE

4. Open any project

5. During the opening of a project, the run widget will be blue for a while
![image](https://user-images.githubusercontent.com/8819844/183929028-5a1ff833-831f-433e-a3a9-84607ddcd7ae.png)

---

1. Use a custom them: **File \> Settings \> Appearance & Behavior \> Appearance \> Theme** where the main color is not blue

2. Enable new UI:

   | ide.experimental.ui | true |
   | --- | --- |

3. Reload IDE

4. Open any project and run tests

5. During the running of tests till they are not finished the color is not correct
![image3](https://user-images.githubusercontent.com/8819844/183929428-b1230bb9-def4-4172-a804-05cde968545a.png)

### Expected behavior

The color for the run widget during a load of a project or a run state has to be correct.
![image1](https://user-images.githubusercontent.com/8819844/183929066-1744b337-8f95-40f6-af6c-c250bca5bc34.png)

### Material Theme Version

7.7.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.2
Build #PS-222.3345.135, built on July 28, 2022
Licensed to Andrii Dorotiuk
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-43-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    editor.caret.width=1
    ide.experimental.ui.navbar.scroll=true
    run.processes.with.pty=TRUE
    vcs.new.widget=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.3)
    pronskiy.elephpant (0.1.1)
    org.elasticsearch4idea (2022.2.0-222)
    name.kropp.intellij.makefile (222.3345.108)
    intellij-awk (0.3.2)
    indent-rainbow.indent-rainbow (2.0.2)
    de.femtopedia.diffplugin (2.1.8)
    com.ultrahob.zerolength.plugin (0.95)
    com.intellij.properties (222.3345.108)
    com.hjf.redis.manager.redis-manager (1.4.1)
    com.alayouni.ansiHighlight (22.2.2)
    String Manipulation (9.5.1)
    GrepConsole (12.14.211.6693.0)
    zielu.gittoolbox (212.9.7)
    uk.co.ben-gibson.remote.repository.mapper (4.1.8)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (65.1.0)
    com.majera.intellij.codereview.gitlab (2022.4.0.221)
    de.espend.idea.php.annotation (8.2.3)
    com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.5)
    com.magento.idea.magento2plugin (4.3.1)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
    izhangzhihao.rainbow.brackets (6.25)
    com.chrisrm.idea.MaterialThemeUI (7.7.1)
    ir.msdehghan.plugins.ansible (0.92)
    fr.adrienbrault.idea.symfony2plugin (2022.1.232)
    com.github.blarc.gitlab-template-lint-plugin (0.0.12)
    org.jetbrains.plugins.node-remote-interpreter (222.3345.108)
    ru.adelf.idea.dotenv (2022.2)
    pro.bashsupport (2.1.9.222)

Current Desktop: ubuntu:GNOME
```

### Logs/Screenshots

```shell
Plugin settings:
https://files.slack.com/files-pri/TB9PLQM0U-F03T03NSWP2/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03SP1HRKJM/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03S7DGBD2R/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03S3PM7CMC/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03S7DJ9XTP/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03S3PNV01L/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03SCR7EBT6/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03T03UPY3A/image.png
https://files.slack.com/files-pri/TB9PLQM0U-F03RVR0SF71/image.png
```

**Comment by mallowigi** [comment] 2022-08-15 19:07
I updated the latest colors. I could not reproduce the issue where it appears blue at start, but theoretically it should be fixed.

**Comment by an2riy** [comment] 2022-08-16 08:18
Could you give me the new plugin version to check or should I wait for the update?

**Closed** 2022-08-27 15:48 UTC
Labels: bug
