### ISSUE TITLE
[Bug]: Lambda is null

### ISSUE THREAD

**Issue by CarinaSchoppe** [mallowigi/material-theme-issues#228] opened 2022-09-20 17:55 UTC
### Describe the bug

Nullpointer exception

### To Reproduce

dont really know. 
Ive just opend my Unity Project in Rider

### Expected behavior

No exception

### Material Theme Version

v7.10.1

### IDE

Rider

### System Info

```shell
Build #RD-222.4167.23, built on September 9, 2022

Licensed to Carina Sophie Schoppe
Subscription is active until February 12, 2023.
For educational use only.

Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET 6.0.6
```

### Logs/Screenshots

```shell
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViewsFont_u24lambda_u2d16_u24lambda_u2d15" is null
	at com.mallowigi.idea.MTThemeManager.refreshProjectViewsFont(MTThemeManager.kt:562)
	at com.mallowigi.idea.MTThemeManager.applyCustomTreeFont(MTThemeManager.kt:553)
	at com.mallowigi.idea.MTThemeManager.applyFonts(MTThemeManager.kt:525)
	at com.mallowigi.idea.MTLafComponent.lookAndFeelChanged(MTLafComponent.kt:75)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:448)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy2/jdk.proxy2.$Proxy61.lookAndFeelChanged(Unknown Source)
	at com.intellij.ide.ui.laf.LafManagerImpl.notifyLookAndFeelChanged(LafManagerImpl.java:846)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:836)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:311)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:238)
	at com.mallowigi.idea.MTLafComponent.activateTheme(MTLafComponent.kt:214)
	at com.mallowigi.idea.MTLafComponent.onSettingsChanged(MTLafComponent.kt:183)
	at com.mallowigi.idea.MTLafComponent$initComponent$2.configChanged(MTLafComponent.kt:132)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy3/jdk.proxy3.$Proxy190.configChanged(Unknown Source)
	at com.mallowigi.idea.config.application.MTConfig.fireChanged(MTConfig.java:359)
	at com.mallowigi.idea.config.application.MTConfig.activateFreePlan(MTConfig.java:534)
	at com.mallowigi.idea.license.MTLicenseManager.switchToFreePlan$lambda-0(MTLicenseManager.kt:120)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment] 2022-09-20 18:02
Duplicate of https://github.com/mallowigi/material-theme-issues/issues/226, will be fixed next release

**Closed** 2022-09-20 18:02 UTC
Labels: bug
