### ISSUE TITLE
[Bug]: New File dialog input area is too small 

### ISSUE THREAD

**Issue by dudong0726** [mallowigi/material-theme-issues#122] opened 2022-04-06 02:01 UTC
### Describe the bug

New File dialog input area is too small 

### To Reproduce

1. new File or new Javaclass
2. dialog input area is too small

### Expected behavior

show normal

### Material Theme Version

6.16.2

### IDE

IntelliJ IDEA

**Comment by dudong0726** [comment] 2022-04-06 02:04
![20220406095641](https://user-images.githubusercontent.com/1704803/161881150-f2686324-72c0-421c-9b24-27888466ab48.jpg)

**Comment by mallowigi** [comment] 2022-04-06 05:13
One fix breaks another... I think I know what might cause it. If it's what I think I'll release yet another hotfix. Good thing I didn't deploy to 2022 yet...

**Comment by mallowigi** [comment] 2022-04-06 07:29
Are you using compact fields ?

**Comment by dudong0726** [comment] 2022-04-08 02:00
> Are you using compact fields ?

yes, i uncheck the compact fields, its fixed.

**Comment by mallowigi** [comment] 2022-04-08 11:54
duplicate of 121

**Closed by mallowigi** 2022-04-08 11:54 UTC
Labels: bug
