### ISSUE TITLE
[Bug]: Hover Effect is Missing in Android Studio Giraffe Main Tool Bar for Run Widgets - Moonlight(Material) Theme

### ISSUE THREAD

**Issue by BolisettySujith** [mallowigi/material-theme-issues#374] opened 2023-07-27 10:36 UTC
### Describe the bug

I'm using Moonlight(Material) theme in Android Studio, and when I upgraded my Android Studio from Flamingo (2022.2.1) to Giraffe (2022.3.1) version. In the New UI of Giraffe version, the run widgets tool bar doesn't have any hover effect. In general hover effect can describe whether the button is clickable or not, so as it was missing in it, it finding hard to check whether the button in clickable or not unless I click on it.

![image](https://github.com/mallowigi/material-theme-issues/assets/73323807/bb9d08ce-4c06-45fd-8897-f905953c7178)

![image](https://github.com/mallowigi/material-theme-issues/assets/73323807/4ea7aa13-8786-4478-b268-fe1cb3a12939)

### To Reproduce

1. Install the latest Android Studio Giraffe (2022.3.1) version.
2. Use the Moonlight (Material) Theme 
3. Try to hover on the Main Tool Bar Run Widgets

### Expected behavior

When hover on the buttons on the Main Tool bar run widgets, it should have some hover effects.

### Material Theme Version

v8.4.1

### IDE

Android Studio

**Comment by mallowigi** [comment] 2023-07-27 12:31
This is fixed in later versions. Android Studio is always lagging behind (2022), so there's nothing we can do (we don't work on older versions).

I suggest you install the Canary version and see for yourself if the problem is occuring there.

**Closed by mallowigi** 2023-07-27 12:31 UTC
Labels: bug
