### ISSUE TITLE
[Bug]: Atom Material Icons plugin triggers full project re-indexing

### ISSUE THREAD

**Issue by SLukashenko** [mallowigi/material-theme-issues#295] opened 2023-01-05 10:53 UTC
### Describe the bug

2023-01-03 09:21:00,585 [  62628]   INFO - #c.i.u.i.UnindexedFilesScanner - Cancelled indexing of project
2023-01-03 09:21:00,844 [  62887]   INFO - c.i.s.k.s.d.SpaceKtsFileDetector - SpaceKtsFileDetector
2023-01-03 09:21:00,876 [  62919]   INFO - #c.i.u.i.UnindexedFilesScanner - Started scanning for indexing of project. Reason: File type change: added - null, removed - null

It appears that plugin calls  com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl#fireFileTypesChanged() and triggers full project indexing. In logs of user who reported this behaviour we can see that FileTypeManagerImpl#fireFileTypesChanged() was called twice on single IDE start

### To Reproduce

Unfortunately I cannot share user log files or give more details on the issue

### Expected behavior

Plugin should not cancel project indexing

### Material Theme Version

80.0.0

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment] 2023-01-05 16:44
I can't reproduce this behavior. I've been using my plugin for as long as I can think of and this simply doesn't happen.

If you or your users experience this issue constantly, please connect to the slack channel so we can debug it thoroughly. Until then, I'm closing this.

**Closed by mallowigi** 2023-01-05 16:44 UTC
Labels: bug
