### ISSUE TITLE
Both tabs highlighted in split pane mode 

### ISSUE THREAD

**Issue by oldium** [mallowigi/material-theme-issues#395] opened 2023-09-11 14:03 UTC
### Describe the bug

When in split-pane mode, both tabs are highlighted as active, not only the one with cursor. 

### To Reproduce

1. Right-click on current tab, select Split Right.
2. Observe that both tabs are highlighted as active.

### Expected behavior

The tab without cursor should be dimmed.

### Material Theme Version

v8.11.0

### IDE

DataGrip

### System Info

```shell
DataGrip 2023.2.1
Build #DB-232.9559.28, built on August 16, 2023
Licensed to ***********
You have a perpetual fallback license for this version.
Subscription is active until ********.
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    editor.focus.mode.color.light=5a5d63
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5a5d63

Non-Bundled Plugins:
    com.tabnine.TabNine (1.2.0)
    com.alayouni.ansiHighlight (23.2.0)
    dev.polek.adbwifi (1.2.5)
    ski.chrzanow.foldableprojectview (1.1.6)
    com.tang (1.4.8-IDEA231)
    mobi.hsz.idea.gitignore (4.5.1)
    com.chrisrm.idea.MaterialThemeUI (8.11.0)
```

### Logs/Screenshots

![image](https://github.com/mallowigi/material-theme-issues/assets/1260936/612ffa08-7e73-4182-85e7-3984480439a0)

**Comment by mallowigi** [comment] 2023-09-12 14:47
It's by design. You can change the color in the Color Scheme Settings > Tabs Underline Inactive

**Comment by oldium** [comment] 2023-09-12 15:10
> It's by design. You can change the color in the Color Scheme Settings > Tabs Underline Inactive

The inactive tab is rendered with active underline color, which looks like a bug. When I disable Material UI plugin, the tabs are rendered correctly.

Without Material UI plugin:
![image](https://github.com/mallowigi/material-theme-issues/assets/1260936/26bc468c-d7ba-4352-8328-89b15e26885b)

**Comment by mallowigi** [comment] 2023-09-12 15:18
I see, you're right, I disabled it at the time.

I'll add this to the backlog.

**Comment by mallowigi** [comment] 2023-09-23 07:45
I just checked in more detail, and I was right before. Closing.

**Comment by oldium** [comment] 2023-09-23 09:39
So what should I do in order to fix this actually, please? When I enable Material UI, both tabs are rendered as highlighted-active, this is wrong. The one without cursor should have a different (dimmed/gray) highlighting color.

**Comment by mallowigi** [comment] 2023-09-23 10:37
Check the underline tab color in the color scheme and assign it the value you want.

**Comment by oldium** [comment] 2023-09-23 12:13
Ok, thanks, I found it. I had to _set_ the “Underline inactive” color (previously _unset_) to simulate the behaviour of IDE without Material UI. I think better would be to have some sensible default in Material UI, so that I am not forced to tune the theme - this is why chose to pay for Material UI - to forget about the theme color details in the first place 😊

![image](https://github.com/mallowigi/material-theme-issues/assets/1260936/94d23d23-80c2-4dca-bb6b-238277421977)

**Comment by mallowigi** [comment] 2023-09-24 11:08
I need to think about it. I can agree on that statement, though the default gray color is not a suitable choice. I'm thinking more about the "disabledColor" or the "textColor".

In any case it won't happen right now.

**Comment by mallowigi** [comment] 2023-09-29 10:23
I did it in the end. Should be available on the latest version.

**Closed** 2023-09-29 10:23 UTC
Labels: Feature request

**Comment by oldium** [comment] 2023-09-29 11:54
Thanks, unfortunately it does not do anything for me. It works _somehow_ for themes with Material in the name, but I am used to use the “Dark” theme with Lime as an accent color plus Material UI tweaks.

I tried to create custom theme from the Dark one (Material Theme UI/Custom Theme, select Color Scheme: Dark, change the Accent Color to 7CB342), but still no gray for the inactive selected tab. When I load different theme with Load From... Material Darker, the inactive selected tab color works (it is gray), but the active tab color is orange independently on the selected Accent Color.

Also when I select the “Martial Darker” theme in Material Theme UI/Settings, the changed Accent color has no effect on tab underline color.

I am really not sure if I am doing something wrong, but for me the only working combination is to select the Dark theme in the Material Theme UI/Settings, change the accent color to Lime and override the “Underling inactive” tab color.

**Comment by mallowigi** [comment] 2023-09-29 13:25
> Thanks, unfortunately it does not do anything for me. It works somehow for themes with Material in the name, but I am used to use the “Dark” theme with Lime as an accent color plus Material UI tweaks.
As I said previously, this is a color scheme setting. That update updated the bundled color schemes to change the inactive tab underline to the same color as the "Text Color", e.g. the trees foreground color. What happens in other schemes is not of my resort.

> I also tried to create custom theme from the Dark one (Material Theme UI/Custom Theme, select Color Scheme: Dark, change the Accent Color to 7CB342), but still no gray for the inactive selected tab. When I load different theme with Load From... Material Darker, the inactive selected tab color works (it is gray), but the active tab color is orange independently on the selected Accent Color (in Material Theme UI/Custom Theme/Accent Color).

This might be an issue. The tab color is of the color scheme, but the plugin applies an additional layer on top of the color scheme, which is used for the custom _Tab Highlight Position_, as well as the _Custom Tab Highlight Color_. But if you don't have the _Custom Tab Highlight Color_ enabled, it uses the one defined in the color scheme, and only if not defined it will resort to use the Accent Color. If it's not the case, please open an issue about it specifically, with reproducible steps.


So for short, here are what dictates the behavior of the tabs colors:
- For the inactive tab, it's the color scheme only
- For the active tab, it's the following:
	- If "Per-project Settings" is enabled, and "Custom Highlight Color" is set, it uses that color
	- If "Custom Highlight Color" is set, it uses that color
	- Otherwise it uses the color scheme's color	

More info: https://material-theme.com/docs/configuration/tab-settings/#active-tab-highlighter

**Comment by oldium** [comment] 2023-09-29 14:53
I am using the Dark color scheme, which is the official JetBrains scheme and does not have the _Editor/Tabs/Underline_ nor _Editor/Tabs/Underline inactive_ set in the color scheme.

I am not using the _Active Tab Highlight Color_ (unset) in the _Appearance & Behavior/Material Theme UI/Settings/Tabs_ if you mean this one.

When I check the _Editor/Color Scheme/General_, it shows both _Editor/Tabs/Underline_ and _Editor/Tabs/Underline inactive_ unset for the IntelliJ color schemes (like “Dark”), but both are set for all Material color schemes (this matches the default accent color).

The problem with accent color for tab undelines in Material color schemes is probably independent on this issue, so I can create a separate issue for it.

For this issue I am still using the same steps to reproduce it. It is 100% reproducible also on clean setup (I used CLion 2023.2.2 on Linux for this test):

1. [Restore the default settings](https://www.jetbrains.com/help/idea/configuring-project-and-ide-settings.html#restore-defaults).
2. During startup select Create new project...
3. Install the Material Theme UI.
4. Restart the IDE to activate the plugin.
5. Move one of the opened tabs to the right to have two tabs visible at the same time.
6. Observe the tab underline color.

On my system the IDE starts with the Dark theme after the Restore Default Settings step.
