### ISSUE TITLE
[Bug]: Some input boxes are too small

### ISSUE THREAD

**Issue by Maxmyd** [mallowigi/material-theme-issues#123] opened 2022-04-06 12:51 UTC
### Describe the bug

Hello,
Text in some input fields is barely visible.
![image](https://user-images.githubusercontent.com/1541735/161977185-cfaa9fcf-3453-4daf-824b-118d3491423c.png)
![image](https://user-images.githubusercontent.com/1541735/161977299-f1be0575-dc0e-4073-9511-6aa34baf10c2.png)

### To Reproduce

Image 1
1. Click on branch name to see branch list
2. Start typing text in the search field

Image 2
1. Open Nuget window
2. Start typing text in the search field

### Expected behavior

The entire text in the input field must be visible

### Material Theme Version

v6.16.2

### IDE

Rider

### System Info

```shell
JetBrains Rider 2021.3.4
Build #RD-213.7172.34, built on March 23, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 20
```

**Comment by Maxmyd** [comment] 2022-04-06 19:42
Yes, it's checked in settings. I unchecked it and now it's OK. Looks like it was too compact :)
BTW few days ago I had the same bug in "Create branch" dialog window, which is fixed after recent update.

**Comment by mallowigi** [comment] 2022-04-08 11:54
closing because duplicate of 121

**Closed by mallowigi** 2022-04-08 11:54 UTC
Labels: bug
