### ISSUE TITLE
Intermittent Errors on Startup (or Settings Sync from JetBrains)

### ISSUE THREAD

**Issue by CanisHelix** [mallowigi/material-theme-issues#64] opened 2022-01-26 01:02 UTC
**Describe the bug**
Intermittent Errors on Startup (Most common).

Can also occur randomly throughout the day when using multiple PC's and a Settings Sync from JetBrains occurs. In both instances, a restart of Rider will resolve it, hence it is intermittent, but most commonly on the first start of Rider for UE of the day.

PC1

> java.lang.NullPointerException: getBorder(LIST_FOCUSED_S…CTION_BACKGROUND_PAINTER) must not be null
	at com.mallowigi.idea.utils.MTUI$List.getListFocusedSelectionPainter(MTUI.kt:201)
	at com.mallowigi.idea.ui.MTRowPainter.paint(MTRowPainter.kt:122)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:254)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:330)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:244)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5270)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1063)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3958)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

PC2

> java.lang.NullPointerException: getBorder(LIST_FOCUSED_S…CTION_BACKGROUND_PAINTER) must not be null
	at com.mallowigi.idea.utils.MTUI$List.getListFocusedSelectionPainter(MTUI.kt:201)
	at com.mallowigi.idea.ui.MTRowPainter.paint(MTRowPainter.kt:122)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:254)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:330)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:244)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5270)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1063)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3958)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce**
Open Rider for Unreal 2021.3 or 2021.3.1, error happens on the Project Selection Screen.

**Expected Behavior**
I expect the theme to be applied properly, or at least leave the UI in a usable state.

**Environment**
PC1
Rider for Unreal Engine 2021.3.1
Build #RDCPPP-213.6461.87, built on January 23, 2022
Runtime version: 11.0.13+7-b1751.21 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows Server 2019 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.balloon.shadow.size=0
    rider.new.toolbar.force.enable.on.migration=true
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (6.12.2)
    com.mallowigi (54.1.0)

PC2
Rider for Unreal Engine 2021.3.1
Build #RDCPPP-213.6461.87, built on January 24, 2022
Runtime version: 11.0.13+7-b1751.21 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 36
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.balloon.shadow.size=0
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false
    rider.new.toolbar.force.enable.on.migration=true
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.intellij.javafx (1.0.3)
    com.chrisrm.idea.MaterialThemeUI (6.12.2)
    com.mallowigi (54.1.0)

**Screenshots**
PC1
![image](https://user-images.githubusercontent.com/7948640/151084932-6188d1bf-3303-4143-8a45-bc41e8f83055.png)

PC2
![image](https://user-images.githubusercontent.com/7948640/151085633-fd7bb7c1-3caf-4cbf-9f37-7bb79db33333.png)

**Comment by CanisHelix** [comment] 2022-01-26 01:03
In addition to the above, this occurs on OSX versions too, not just Windows.

**Comment by mallowigi** [comment] 2022-01-26 07:48
Light theme I assume? If then it's a duplicate of #61

**Comment by CanisHelix** [comment] 2022-01-27 00:44
Material Darker, is the only theme I ever use. Interestingly I have not had this occur in the Linux builds of Rider for UE.

The harder log/screenshot to get is when this happens randomly during usage. <-- I believe this is related to IDE Setting Sync as once I turned that off, the randomly occurring one's stopped happening.

No worries, just wanted to report it.

**Comment by neclimdul** [comment] 2022-01-27 20:01
I got a similar crash in PhpStorm with dark theme with linux.
Posted to the wrong repo by accident but details are here: https://github.com/ChrisRM/material-theme-jetbrains/issues/1859#issue-1115527729

**Comment by neclimdul** [comment] 2022-01-27 20:08
fwiw, I figured out how I ended up in the wrong repo.

1) Crash linked to your profile
2) Clicked on the top repo in the profile spread which points "material-theme-jetbrains"

Unfortunately, that link doesn't point to this repo, it points to the other one. The message about being "archived" was pretty deep in the readme and doesn't have the archive banner so just posted away thinking I was in the correct spot.

**Comment by mallowigi** [comment] 2022-01-27 20:15
Someone else said that in the past but I changed it in the plugin page since then, so it's a bit weird but would explain some people suddenly ended up creating issues here.

Maybe it's a cache issue, or maybe it occured on previous IDE?

**Comment by neclimdul** [comment] 2022-01-27 20:28
sorry, no the link was to your _github_ profile. This link:
![image](https://user-images.githubusercontent.com/82823/151438356-25816c4f-dd6e-4513-8c68-c7e84da1b931.png)

**Comment by CanisHelix** [comment] 2022-01-28 05:48
After a few hours, switched to a different app and back, randomly lost theme. No errors, no warnings. Material Darker is still chosen as can be seen in the status bar. This is a rare occurrence, but might be linked overall.

Restarting the IDE fixes it up again.

![image](https://user-images.githubusercontent.com/7948640/151494017-7a903fce-8200-4a1a-a8f9-300a0d292f51.png)

**Closed** 2022-03-22 05:03 UTC
Labels: duplicate, sync
