### ISSUE TITLE
Do not show radio boxes

### ISSUE THREAD

**Issue by yhan219** [mallowigi/material-theme-issues#23] opened 2021-09-27 06:57 UTC
**Describe the bug**

When I install this plugin,my setting dialog is
<img width="982" alt="2021-09-27 145047" src="https://user-images.githubusercontent.com/12593660/134858558-2b4ff750-e602-4855-8bb1-f4a3187ef90b.png">

and It is normal after uninstall
![image](https://user-images.githubusercontent.com/12593660/134858929-223f2d71-0dbf-4f2d-82c7-8e3789c32039.png)

I've set up some things on the plugin before, but now I don't know what to set because the radio box can't be seen

**Environment**

```
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 27, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.2.4), com.mallowigi (41.1.0), uk.co.ben-gibson.remote.repository.mapper (3.3.5), org.sonarlint.idea (5.3.0.36775), com.liuzhihang.doc-view (1.1.13), com.alibaba.p3c.smartfox (2.1.1), MyBatisLog (2021.5.1), String Manipulation (8.15.203.000.3), zielu.gittoolbox (212.7.11), com.codota.csp.intellij (4.2.9), JRebelPlugin (2021.3.2), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), cn.yiiguxing.plugin.translate (3.1.1), de.endrullis.idea.postfixtemplates (2.12.1.212), me.jinghong.restful.toolkit (1.0.0), izhangzhihao.rainbow.brackets (6.21), pro.bashsupport (2.0.5.212), com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (2.9.6-183-204)
Kotlin: 212-1.5.31-release-546-IJ4638.7
```

**Comment by mallowigi** [comment] 2021-09-27 16:49
duplicate of #22

**Closed by mallowigi** 2021-09-27 16:49 UTC
