### ISSUE TITLE
[Bug]: Incompatibility of version 8.9.0 with DataGrip 2023.2

### ISSUE THREAD

**Issue by dwyart** [mallowigi/material-theme-issues#370] opened 2023-07-21 14:15 UTC
### Describe the bug

Got DataGrip upgraded today and even if Material Theme was also upgraded, it got broken at restart: all menus and dialogs are the "native" ones, this gives the same behavior as disabling Material Theme completely.

### To Reproduce

Test the plugin with DataGrip 2023.2

### Expected behavior

Works as with DataGrip 2023.1

### Material Theme Version

v8.9.0

### IDE

DataGrip

**Comment by mallowigi** [comment] 2023-07-22 06:54
Can't reproduce. Have you tried reinstalling the plugin?

**Comment by dwyart** [comment] 2023-07-22 07:28
Yes, I can reproduce the issue even after uninstalling and reinstalling.

As this new release of DG is very recent, let's wait a few days to check if other users can reproduce it.

**Comment by dwyart** [comment] 2023-07-22 08:51
Not sure this is important, I use the Linux version of DataGrip.

**Comment by mallowigi** [comment] 2023-07-22 09:25
Can you provide a list of plugins as well as your system information (you can have it in the about window)

**Comment by dwyart** [comment] 2023-07-22 13:27
Plugins that relates to UI are:
- Atom Material Icons
- Solarized Themes
(there are also bundled color themes, but I do not use them)
Disabling them has no impact on the behavior of Material Theme.
System info:
```
DataGrip 2023.2
Build #DB-232.8660.111, built on July 19, 2023
Licensed to Damien Wyart
Subscription is active until December 7, 2023.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.3.0-2-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    editor.focus.mode.color.light=657b83
    ide.editor.tab.selection.animation=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=657b83
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.4lex4.intellij.solarized (2.4.0)
    bundled-datagrip-help (232.8660.111)
    org.intellij.plugins.markdown (232.8660.88)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    com.intellij.bigdatatools.core (232.8660.142)
    com.intellij.bigdatatools.binary.files (232.8660.142)
    com.intellij.bigdatatools.rfs (232.8660.142)
    com.intellij.bigdatatools.metastore.core (232.8660.142)
    com.mallowigi (91.0.0)
    zielu.gittoolbox (500.0.13+213)
    mobi.hsz.idea.gitignore (4.5.1)
    com.chrisrm.idea.MaterialThemeUI (8.9.0)
    com.intellij.bigdatatools.flink (232.8660.142)
    com.intellij.bigdatatools.spark (232.8660.142)
    com.intellij.bigdatatools.zeppelin (232.8660.142)
    com.intellij.bigdatatools.kafka (232.8660.142)
    com.intellij.bigdatatools (232.8660.142)

Current Desktop: i3
```

**Comment by dwyart** [comment] 2023-07-24 09:15
Thanks, had not been able to spot the error on my side

**Comment by mallowigi** [comment] 2023-07-24 09:17
What theme are you using ?

**Comment by mqj0712** [comment] 2023-07-24 09:36
> What theme are you using ?

Is this question for me?  I am using the native theme - IntelliJ Light, seems my issue is not the same one that @dwyart raised.

**Comment by RobertTheDude** [comment] 2023-07-24 19:29
Having the same issue - but in WebStorm 2023.2

**Comment by mallowigi** [comment] 2023-07-25 11:39
what theme are you using?

**Comment by RobertTheDude** [comment] 2023-07-25 13:19
I went back to Material Theme UI v8.8.1 (working fine), and am using  the “Sandy Beach Theme”.

Whenever I have Material Theme UI v8.9.0, I get no UI at all except the 1 menu “WebStorm”.  If I uninstall Material Theme UI v8.9.0 and re-install v8.8.1, everything works fine.

**Comment by mallowigi** [comment] 2023-07-25 13:36
Seems like a duplicate of the other issue. I'll investigate that one, thanks

**Closed by mallowigi** 2023-07-25 13:36 UTC
Labels: bug
